version: '3.6'
services:
    node:
        build: docker/
        volumes:
            - './:/var/www/app'
        ports:
            - '3000:3000'
        command:
            - /bin/sh
            - -c
            - npm install && npm start
        depends_on:
            - mariadb
    mariadb:
        image: 'mariadb:10.3'
        volumes:
            - ./sql/emotion.sql:/docker-entrypoint-initdb.d/emotion.sql
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=emotion
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=admin
