version: '3.6'
services:

    node:
        build: docker/
        volumes:
            - './:/var/www/app'
        ports:
            - '3000:3000'
        command:
            - /bin/sh
            - -c
            - npm install && npm start

    mariadb:
        image: 'mariadb:10.3'
        volumes: 
            - './docker/database:/var/lib/mysql'
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=emotion
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=admin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=mariadb
        ports:
            - 8080:80
        volumes:
            - docker/sessions
        links:
            - mariadb