-- MySQL Script generated by MySQL Workbench
-- jeu. 25 juil. 2019 15:10:18 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema emotion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema emotion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `emotion` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;

USE `emotion` ;

-- -----------------------------------------------------
-- Table `emotion`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emotion`.`users` (
  `idusers` INT(11) NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `birthday` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `address` VARCHAR(45) NOT NULL,
  `phoneNumber` INT(11) NOT NULL,
  `driverLicence` VARCHAR(45) NOT NULL,
  `roles` LONGTEXT COLLATE 'utf8mb4_bin' NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `pointFidelity` INT(11) NULL DEFAULT NULL,
  `username` VARCHAR(45) NOT NULL,
  `tokenResetPassword` VARCHAR(255) NULL DEFAULT NULL,
  `tokenValidateAccount` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `emotion`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emotion`.`location` (
  `idlocation` INT(11) NOT NULL AUTO_INCREMENT,
  `startDate` DATETIME NOT NULL,
  `endDate` DATETIME NOT NULL,
  `users_idusers` INT(11) NOT NULL,
  `cancelLocation` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idlocation`),
  INDEX `fk_location_users1_idx` (`users_idusers` ASC),
  CONSTRAINT `fk_location_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `emotion`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `emotion`.`offers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emotion`.`offers` (
  `idoffers` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `price` INT(11) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `penality` VARCHAR(45) NOT NULL,
  `nbKm` INT(11) NOT NULL,
  `pointFidelityOffers` INT(11) NOT NULL,
  `location_idlocation` INT(11) NULL DEFAULT NULL,
  `hiddenOffers` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idoffers`),
  INDEX `fk_offers_location1` (`location_idlocation` ASC),
  CONSTRAINT `fk_offers_location1`
    FOREIGN KEY (`location_idlocation`)
    REFERENCES `emotion`.`location` (`idlocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `emotion`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emotion`.`vehicle` (
  `idvehicle` INT(11) NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `serialNumber` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `licensePlate` VARCHAR(45) NOT NULL,
  `nbKm` INT(11) NOT NULL,
  `datePurchase` DATETIME NOT NULL,
  `price` INT(11) NOT NULL,
  `available` INT(11) NOT NULL,
  `lising` INT(11) NOT NULL,
  `offers_idoffers` INT(11) NULL DEFAULT NULL,
  `typeVehicle` TINYINT(1) NOT NULL,
  `imgVehicle` VARCHAR(45) NULL DEFAULT 'default.jpg',
  PRIMARY KEY (`idvehicle`),
  INDEX `fk_vehicle_offers1` (`offers_idoffers` ASC),
  CONSTRAINT `fk_vehicle_offers1`
    FOREIGN KEY (`offers_idoffers`)
    REFERENCES `emotion`.`offers` (`idoffers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
