-- MySQL Script generated by MySQL Workbench
-- jeu. 25 juil. 2019 16:04:35 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `emotion` ;
-- -----------------------------------------------------
-- Schema emotion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `emotion` DEFAULT CHARACTER SET utf8 ;
USE `emotion` ;

-- -----------------------------------------------------
-- Table `emotion`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emotion`.`users` (
  `idusers` INT(11) NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `birthday` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `address` VARCHAR(45) NOT NULL,
  `phoneNumber` INT(11) NOT NULL,
  `driverLicence` VARCHAR(45) NOT NULL,
  `roles` JSON NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `pointFidelity` INT NULL,
  `username` VARCHAR(45) NOT NULL,
  `tokenResetPassword` VARCHAR(255) NULL ,
  `tokenValidateAccount` VARCHAR(255) NULL ,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB

-- -----------------------------------------------------
-- Table `emotion`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emotion`.`location` (
  `idlocation` INT NOT NULL AUTO_INCREMENT,
  `startDate` DATETIME NOT NULL,
  `endDate` DATETIME NOT NULL,
  `users_idusers` INT NOT NULL,
  `cancelLocation` BOOLEAN NOT NULL DEFAULT 0,
  `pointFidelityUsed` INT NULL,
  PRIMARY KEY (`idlocation`),
  CONSTRAINT `fk_location_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `emotion`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB

-- -----------------------------------------------------
-- Table `emotion`.`offers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emotion`.`offers` (
  `idoffers` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `penality` VARCHAR(45) NOT NULL,
  `nbKm` INT NOT NULL,
  `pointFidelityOffers` INT NOT NULL,
  `location_idlocation` INT NULL,
  `hiddenOffers` BOOLEAN NOT NULL DEFAULT 1,
  PRIMARY KEY (`idoffers`),
  CONSTRAINT `fk_offers_location1`
    FOREIGN KEY (`location_idlocation`)
    REFERENCES `emotion`.`location` (`idlocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB

-- -----------------------------------------------------
-- Table `emotion`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emotion`.`vehicle` (
  `idvehicle` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `serialNumber` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `licensePlate` VARCHAR(45) NOT NULL,
  `nbKm` INT NOT NULL,
  `datePurchase` DATETIME NOT NULL,
  `price` INT NOT NULL,
  `available` INT NOT NULL,
  `lising` INT NOT NULL,
  `offers_idoffers` INT NULL,
  `typeVehicle` BOOLEAN NOT NULL,
  `imgVehicle` VARCHAR(45) NULL DEFAULT 'default.jpg',
  PRIMARY KEY (`idvehicle`),
  INDEX `fk_vehicle_offers1` (`offers_idoffers` ASC),
  CONSTRAINT `fk_vehicle_offers1`
    FOREIGN KEY (`offers_idoffers`)
    REFERENCES `emotion`.`offers` (`idoffers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
